PREFIX = "/"
GAME_CHANNEL = "основной-штаб"
WAR_CHANNEL = "военные-сводки"
ALLIANCE_CATEGORY = "Альянсы"

HOURS_PER_MONTH = 2
TICKS_PER_MONTH = HOURS_PER_MONTH * 3600
BATTLE_ROUND_INTERVAL_MINUTES = 30
BATTLE_RESPONSE_TIMEOUT_MINUTES = 10